### ISSUE TITLE
device_tracker entity: 'NoneType' object has no attribute 'async_create_task'

### ISSUE THREAD

**Issue by ufozone** [ufozone/ha-zcs-mower#86]
```
[homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zcsmower/device_tracker.py", line 120, in _get_location_history
    self.hass.async_create_task(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```

**Comment by ufozone** [comment]
Related to #79
